### ISSUE TITLE
ImportError: No module named Image

### ISSUE THREAD

**Issue by raphaeloliveira** [jlindenbaum/res-resizer#11]
I'm getting 

Traceback (most recent call last):
  File "/usr/bin/android-res-resize.py", line 15, in <module>
    import Image
ImportError: No module named Image

could someone help me?

**Comment by jlindenbaum** [comment]
You're missing the Python Image Library. You can install it by running "pip install pil"

**Comment by raphaeloliveira** [comment]
Thnxs!

On Wed, Apr 24, 2013 at 6:23 PM, Johannes Lindenbaum <
notifications@github.com> wrote:

> You're missing the Python Image Library. You can install it by running
> "pip install pil"
> 
> On Wed, Apr 24, 2013 at 3:22 PM, Raphael Oliveira
> notifications@github.com wrote:
> 
> > I'm getting
> > Traceback (most recent call last):
> > File "/usr/bin/android-res-resize.py", line 15, in <module>
> > import Image
> > ImportError: No module named Image
> > 
> > ## could someone help me?
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/jlindenbaum/android-res-resize/issues/11
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/jlindenbaum/android-res-resize/issues/11#issuecomment-16966939
> .

## 

Raphael F. P. de Oliveira

Analista Desenvolvedor de aplicativos móveis na Fisgo
Mestrando em Sistemas de Informação / Desenvolvimento Ágil - PPGI UFRJ
