### ISSUE TITLE
Add support for xxhdpi

### ISSUE THREAD

**Issue by jlindenbaum** [jlindenbaum/res-resizer#13]
Add support for new XXHDPI (480dpi) which is 1.5x XHDPI.

Determine if this should replace XHDPI as default folder, or wait for more devices/adoption. If it does not replace default behaviour a flag should be created that allows execution from within xxhdpi folder, rather than xhdpi.

**Comment by tskulbru** [comment]
A flag sounds more reasonable for now

**Comment by jlindenbaum** [comment]
Fixed this in 0.4.0. Default is now XXHDPI folder. Removed LDPI, as android documentation states it's no longer required, and generated for us.
