### ISSUE TITLE
--prod uses absolute instead of relative path

### ISSUE THREAD

**Issue by jlindenbaum** [jlindenbaum/res-resizer#9]
When using `--prod` option it's assumed the script is in the android project. Would it make more sense to have it as a path relative to current working directory?

`~/code/myproject/ $ ~/tools/android-res-resize.py --prod` will fail, as `~/tools/` does not have a `res/` directory.

I am assuming that `--prod` could be run from anywhere (easier if it's in $PATH) but would run `--prod` from current working directory.

`~/code/myproject/ $ ~/tools/android-res-resize.py --prod` would work as `~/code/myproject/` has `res/` folder in it.

What's expected behaviour?

**Comment by tskulbru** [comment]
You are absolutely right, it should be relative path
